locales:
  en:
    name: North Sami Keyboards
    description: >-
      Keyboards for North Sámi from the Divvun and Giellatekno groups at UiT.
      For Windows, macOS, Linux, ChromeOS, smartphones and tablets.
      Layouts for Finland, Norway and Sweden.
  nb:
    name: Nordsamiske tastatur
    description: >-
      Tastatur for nordsamisk fra Divvun-gruppa og Giellatekno-gruppene ved UiT.
      For Windows, macOS, Linux, ChromeOS, mobiltelefoner og nettbrett.
      Tilpasset for Finland, Norge og Sverige.
  nn:
    name: Nordsamiske tastatur
    description: >-
      Tastatur for nordsamisk frå Divvun- og Giellatekno-gruppene ved UiT.
      For Windows, macOS, Linux, ChromeOS, mobiltelefonar og nettbrett.
      Tilpassa for Finland, Noreg og Sverige.
  se:
    name: Davvisámi boallobeavddit
    description: >-
      Boallobeavddit davvisámegiela várás Divvun- ja Giellatekno-joavkkuin UiT:s.
      Doaibmá Windowsis, macOS:s, Linuxis, ChromeOS:s, mátketelefovnnain ja dihtordulbosiin.
      Heivehuvvon Norgii, Ruŧŧii ja Supmii.
  sma:
    name: Noerhtesaemien båaloebuertie
    description: >-
      Noerhtesaemien båaloebuertie UiT:n Divvun jïh Giellatekon-dåehkijste daelie
      Windowsisnie, macOS:sne, Linuxisnie, ChromeOS:sne, mobiltelefovnide jïh
      nehtepreerjine jåhta. Nöörjese, Soemese jïh Sveerjese sjïehtesjovveme.
  smj:
    name: Nuorttasáme boallobievde
    description: >-
      Nuorttasáme boallobievde UiT:a Divvun- ja Giellatekno-juohkusijs.
      Windowsij, macOS:aj, Linuxij, ChromeOS:aj, mobijlajda ja pettajda.
      Hiebaduvvam Vuodnaj, Svierigij ja Suobmaj.
  sv:
    name: Nordsamiska tangentbord
    description: >-
      Tangentbord för nordsamiska från Divvun- och Giellatekno-grupperna ved UiT.
      För Windows, macOS, Linux, ChromeOS, mobiltelefoner och surfplattor.
      Anpassade för Finland, Norge och Sverige.
author: 'The Divvun and Giellatekno Groups, UiT Norgga árktalaš universitehta'
copyright: © 2024 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga árktalaš universitehta
