locales:
  en:
    name: North Sami Keyboard
    description: >-
      Keyboards for North Sámi from the Divvun and Giellatekno groups at UiT.
      For Windows, macOS, Linux, ChromeOS, smartphones and tablets.
      Layouts for Finland, Norway and Sweden.
  nb:
    name: Nordsamisk tastatur
    description: >-
      Tastatur for nordsamisk fra Divvun-gruppa og Giellatekno ved UiT.
      For Windows, macOS, Linux, ChromeOS, mobiltelefoner og nettbrett.
      Tilpasset for Finland, Norge og Sverige.
author: 'The Divvun Group, UiT Norgga árktalaš universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga árktalaš universitehta
