locales:
  en:
    name: North Sami Keyboards
    description: >-
      Keyboards for North Sámi from the Divvun and Giellatekno groups at UiT.
      For Windows, macOS, Linux, ChromeOS, smartphones and tablets.
      Layouts for Finland, Norway and Sweden.
  nb:
    name: Nordsamiske tastatur
    description: >-
      Tastatur for nordsamisk fra Divvun-gruppa og Giellatekno-gruppene ved UiT.
      For Windows, macOS, Linux, ChromeOS, mobiltelefoner og nettbrett.
      Tilpasset for Finland, Norge og Sverige.
  nn:
    name: Nordsamiske tastatur
    description: >-
      Tastatur for nordsamisk frå Divvun- og Giellatekno-gruppene ved UiT.
      For Windows, macOS, Linux, ChromeOS, mobiltelefonar og nettbrett.
      Tilpassa for Finland, Noreg og Sverige.
  se:
    name: Davvisámi boallobeavdi
    description: >-
      Boallobeavdi davvisámegiela várás Divvun- ja Giellatekno-joavkkuin UiT:s.
      Doaibmá Windowsis, macOS:s, Linuxis, ChromeOS:s, mátketelefovnnain ja dihtordulbosiin.
      Heivehuvvon Supmii, Norgii ja Ruŧŧii.
  sv:
    name: Nordsamiska tangentbord
    description: >-
      Tangentbord för nordsamiska från Divvun- och Giellatekno-grupperna ved UiT.
      För Windows, macOS, Linux, ChromeOS, mobiltelefoner och surfplattor.
      Anpassade för Finland, Norge och Sverige.
author: 'The Divvun and Giellatekno Groups, UiT Norgga árktalaš universitehta'
copyright: © 2024 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga árktalaš universitehta
