trigger:
- master

resources:
  repositories:
    - repository: templates
      type: GitHub
      name: divvun/divvun-ci-config
      endpoint: divvun-ci

jobs:
  - template: repo/templates/keyboards.yml@templates
    parameters:
      name: sme
      packageName: keyboard-sme
      kbdgenFolder: "sme.kbdgen"
      repositoryWin: "https://pahkat.uit.no/repo/windows"
      repositoryMac: "https://pahkat.uit.no/repo/macos"
      languages:
        - projectjjName: giella-sme
          path: usr/share/giella/mobilespellers/sme-mobile.zhfst
          name: sme
