internalName: sme_keyboard

locales:
  en:
    name: &bundleName "North Sami Keyboard"
    description: "Mobile OS keyboards for the North Sami language from the Divvun group at UiT."
  nb:
    name: "Nordsamisk tastatur"
    description: "Mobiltastatur for nordsamisk fra Divvun-gruppa."

author: The Divvun Group, UiT Norgga 치rktala코 universitehta
email: feedback@divvun.no

copyright: (c) 2017 Divvun/Giellatekno/UiT
organisation: UiT Norgga 치rktala코 universitehta

layouts: [sme-mobile, sme_FI-macos, sme_NO-macos, sme_SE-macos, sme_FI-windows, sme_NO-windows, sme_SE-windows]

version: 1.0
build: 1

targets:
  android:
    packageId: no.uit.giella.keyboards.sme
    icon: images/sme-icon.pdf
    keyStore: /Users/brendan/git/softkbdgen/test.keystore
    keyAlias: sme_keyboard

  ios: &AppleID
    codeSignId: "iOS Development"
    provisioningProfileId: Test
    packageId: no.uit.giella.keyboards.sme
    bundleName: *bundleName
    icon: images/sme-icon.png

  osx:
    <<: *AppleID
    icon: images/sme-keyboard-menu-icon.png
    codeSignId: "Developer ID Installer: The University of Tromso (2K5J2584NX)"
    version: 1.0.0-beta2
    resources: doc
    readme: readme.html
    background: background.png
