locales:
  en:
    name: "Divvun's Sami Keyboard"
    description: "A mobile OS keyboard for Northern Sami, Finnish and Norwegian."
  nb:
    name: "Divvun sitt samisktastatur"
    description: "Et mobiltastatur for nordsamisk, finsk og norsk."

author: The Divvun Group, UiT
email: feedback@divvun.no

layouts: [sme, nob, fin]

targets:
  android:
    packageId: so.brendan.keyboards.sami

